name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:         # Permite execução manual

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: yanvigna2  # Seu username do GitHub
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push Snake Animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output        # Branch onde o arquivo SVG será publicado
          build_dir: dist              # Diretório onde o SVG foi salvo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de acesso do GitHub
